language: python
python:
  - "2.7"
env:
  - NEO4J_VERSION="1.9.2"
before_install:
  - ./download_and_install_neo4j.sh $NEO4J_VERSION
install:
  - pip install -U -r requirements_test.txt --use-mirrors
before_script:
  - ./neo4j/bin/neo4j start
script:
  - coverage run --source=sylva sylva/manage.py test accounts data engines graphs schemas base.SchemaTestCase base.UserTestCase
#  - coverage run --source=sylva sylva/manage.py test accounts base data engines graphs schemas
after_success:
  - coveralls
after_script:
  - ./neo4j/bin/neo4j stop
