language: python
python:
  - "2.7"
env:
  - NEO4J_VERSION="1.9.2"
before_install:
  - ./download_and_install_neo4j.sh $NEO4J_VERSION
install:
  - pip install -r requirements_test.txt
  - pip install --allow-all-external argparse==1.2.1
before_script:
  - ./neo4j/bin/neo4j start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install karma
  - npm install karma-jasmine
  - npm install jasmine-core
  - npm install karma-firefox-launcher
  - npm install karma-phantomjs-launcher
script:
  - python sylva/manage.py collectstatic --noinput --settings=sylva.test_settings
  - python sylva/manage.py compress --settings=sylva.test_settings
  - coverage run --source=sylva sylva/manage.py test accounts sylva.tests data engines graphs schemas reports --settings=sylva.test_settings
  - node_modules/karma/bin/karma start sylva/reports/static/app/js/karma.conf.js --single-run --browsers PhantomJS
after_success:
  - coveralls
after_script:
  - ./neo4j/bin/neo4j stop
  - "sh -e /etc/init.d/xvfb stop"
