language: python
python:
  - "2.7"
before_install:
  - sudo service neo4j stop || true
  - sleep 3
  - ./download_and_install_neo4j.sh
  - ./neo4j/bin/neo4j start
  - sleep 7
install: pip install --use-mirrors -r requirements.txt
env:
  - NEO4J_VERSION="1.9.2"
script:
  python Sylva/sylva/manage.py test data graphs schemas
after_success:
  - ./neo4j/bin/neo4j stop
