try:
    from sylva.settings import *
except ImportError:
    pass

DEBUG = False
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

COMPRESS_ENABLED = False  # By default it's the opposite to 'DEBUG'

ENABLE_REPORTS = False
ENABLE_QUERIES = False
ENABLE_ANALYTICS = True

# OPTIONS is a dictionary made available in templates
OPTIONS = {
    "ACCOUNT_FREE": ACCOUNT_FREE,
    "ENABLE_INSTANCES": ENABLE_INSTANCES,
    "ENABLE_INHERITANCE": ENABLE_INHERITANCE,
    "ENABLE_AUTOCOMPLETE_NODES": ENABLE_AUTOCOMPLETE_NODES,
    "ENABLE_AUTOCOMPLETE_COLLABORATORS": ENABLE_AUTOCOMPLETE_COLLABORATORS,
    "ENABLE_SEARCH": ENABLE_SEARCH,
    "ENABLE_SIGNUP": ENABLE_SIGNUP,
    "ENABLE_TYPE_VALIDATION_FORMS": ENABLE_TYPE_VALIDATION_FORMS,
    "ENABLE_QUERIES": ENABLE_QUERIES,
    "ENABLE_REPORTS": ENABLE_REPORTS,
    "ENABLE_ANALYTICS": ENABLE_ANALYTICS,
    "MAINTENANCE_MODE": MAINTENANCE_MODE,
    "PREVIEW_NODES": PREVIEW_NODES,
    "DEFAULT_FROM_EMAIL": DEFAULT_FROM_EMAIL,
    "ACTIVATION_EMAIL_BETA_MESSAGE": ACTIVATION_EMAIL_BETA_MESSAGE,
}
