try:
    from sylva.settings import *
except ImportError:
    pass

ENABLE_REPORTS = True
ENABLE_QUERIES = True
ENABLE_ANALYTICS = True

# OPTIONS is a dictionary made available in templates
OPTIONS = {
    "ACCOUNT_FREE": ACCOUNT_FREE,
    "ENABLE_INSTANCES": ENABLE_INSTANCES,
    "ENABLE_INHERITANCE": ENABLE_INHERITANCE,
    "ENABLE_AUTOCOMPLETE_NODES": ENABLE_AUTOCOMPLETE_NODES,
    "ENABLE_AUTOCOMPLETE_NODES_COMBO": ENABLE_AUTOCOMPLETE_NODES_COMBO,
    "ENABLE_AUTOCOMPLETE_COLLABORATORS": ENABLE_AUTOCOMPLETE_COLLABORATORS,
    "ENABLE_SEARCH": ENABLE_SEARCH,
    "ENABLE_SIGNUP": ENABLE_SIGNUP,
    "ENABLE_TYPE_VALIDATION_FORMS": ENABLE_TYPE_VALIDATION_FORMS,
    "ENABLE_QUERIES": ENABLE_QUERIES,
    "ENABLE_REPORTS": ENABLE_REPORTS,
    "ENABLE_ANALYTICS": ENABLE_ANALYTICS,
    "MAINTENANCE_MODE": MAINTENANCE_MODE,
    "PREVIEW_NODES": PREVIEW_NODES,
    "DEFAULT_FROM_EMAIL": DEFAULT_FROM_EMAIL,
    "ACTIVATION_EMAIL_BETA_MESSAGE": ACTIVATION_EMAIL_BETA_MESSAGE,
}

DEBUG = False
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

TEST = True

COMPRESS_ENABLED = True  # By default it's the opposite to 'DEBUG'
COMPRESS_ROOT = STATIC_ROOT

COMPRESS_URL = STATIC_URL

COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_CONTEXT = {
    'base_template': 'base.html',
    'STATIC_PREFIX': STATIC_URL,
    'as_modal': True,
    'OPTIONS': {
        'ENABLE_ANALYTICS': True
    },
}
